/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-primary-fixed-variant': '#2d486d',
        'surface-dim': '#d8dadc',
        'surface': '#f7f9fb',
        'primary-fixed-dim': '#adc8f5',
        'on-secondary-fixed': '#0b1c30',
        'primary-container': '#1e3a5f',
        'secondary-fixed-dim': '#b7c8e1',
        'secondary-container': '#d0e1fb',
        'on-primary': '#ffffff',
        'on-tertiary-container': '#c69b5f',
        'surface-variant': '#e0e3e5',
        'tertiary-fixed-dim': '#edbf7f',
        'on-error-container': '#93000a',
        'on-background': '#191c1e',
        'secondary-fixed': '#d3e4fe',
        'on-tertiary-fixed': '#291800',
        'on-surface-variant': '#43474e',
        'error-container': '#ffdad6',
        'on-tertiary': '#ffffff',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        'inverse-surface': '#2d3133',
        'on-primary-fixed': '#001c3b',
        'tertiary': '#341f00',
        'background': '#f7f9fb',
        'surface-tint': '#455f87',
        'surface-bright': '#f7f9fb',
        'on-tertiary-fixed-variant': '#60410c',
        'surface-container-highest': '#e0e3e5',
        'tertiary-container': '#503300',
        'primary-fixed': '#d5e3ff',
        'primary': '#022448',
        'error': '#ba1a1a',
        'outline-variant': '#c4c6cf',
        'on-surface': '#191c1e',
        'inverse-primary': '#adc8f5',
        'surface-container-low': '#f2f4f6',
        'secondary': '#505f76',
        'on-secondary-container': '#54647a',
        'on-secondary-fixed-variant': '#38485d',
        'on-secondary': '#ffffff',
        'outline': '#74777f',
        'inverse-on-surface': '#eff1f3',
        'on-primary-container': '#8aa4cf',
        'surface-container-high': '#e6e8ea',
        'tertiary-fixed': '#ffddb2',
        'surface-container': '#eceef0',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '9999px',
      },
      spacing: {
        xs: '4px',
        gutter: '24px',
        xl: '32px',
        'margin-desktop': '40px',
        xxl: '48px',
        md: '16px',
        base: '4px',
        sm: '8px',
        lg: '24px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
