
apiVersion: apps/v1
kind: Deployment
metadata:
  name: validacion
  namespace: sat-qa
spec:
  replicas: 2
  selector:
    matchLabels:
      app: validacion
  template:
    metadata:
      labels:
        app: validacion
    spec:
      containers:
        - name: validacion
          image: sat-validacion:latest
          ports:
            - containerPort: 4002
          envFrom:
            - configMapRef:
                name: sat-config
            - secretRef:
                name: sat-secrets
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
            cpu: "200m"
