apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-reportes
  namespace: sat-qa
spec:
  serviceName: db-reportes
  replicas: 1
  selector:
    matchLabels:
      app: db-reportes
  template:
    metadata:
      labels:
        app: db-reportes
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: reportes
            - name: POSTGRES_USER
              value: reportes
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sat-secrets
                  key: DB_PASSWORD_REPORTES
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
