apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-validacion
spec:
  serviceName: db-validacion
  replicas: 1
  selector:
    matchLabels:
      app: db-validacion
  template:
    metadata:
      labels:
        app: db-validacion
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: "nodo"
                    operator: In
                    values:
                      - "vm1"
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: validacion
            - name: POSTGRES_USER
              value: validacion
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sat-secrets
                  key: DB_PASSWORD_VALIDACION
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 1Gi
