apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-dbs
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pg-dump
              image: postgres:16-alpine
              envFrom:
                - configMapRef:
                    name: sat-config
                - secretRef:
                    name: sat-secrets
              command:
                - sh
                - -c
                - |
                  TIMESTAMP=$(date +%Y%m%d_%H%M%S)
                  pg_dump "$DB_REPORTES_URL" > /backups/reportes_$TIMESTAMP.sql
                  pg_dump "$DB_VALIDACION_URL" > /backups/validacion_$TIMESTAMP.sql
                  pg_dump "$DB_LOGISTICA_URL" > /backups/logistica_$TIMESTAMP.sql
                  echo "Backup completo: $TIMESTAMP"
              volumeMounts:
                - name: backup-storage
                  mountPath: /backups
          restartPolicy: OnFailure
          volumes:
            - name: backup-storage
              persistentVolumeClaim:
                claimName: backup-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
  namespace: sat-qa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
