apiVersion: v1
kind: ConfigMap
metadata:
  name: sat-config
data:
  RABBITMQ_URL: "amqp://rabbitmq:5672"
  RABBITMQ_EXCHANGE: "sat.events"
  DB_REPORTES_URL: "postgres://reportes:password@db-reportes:5432/reportes?sslmode=disable"
  DB_VALIDACION_URL: "postgres://validacion:password@db-validacion:5432/validacion?sslmode=disable"
  DB_LOGISTICA_URL: "postgres://logistica:password@db-logistica:5432/logistica?sslmode=disable"
  SERVICIO_REPORTES_URL: "http://svc-reportes:4001"
  SERVICIO_VALIDACION_URL: "http://svc-validacion:4002"
  SERVICIO_LOGISTICA_URL: "http://svc-logistica:4003"
