apiVersion: v1
kind: ConfigMap
metadata:
  name: sat-config
data:
  RABBITMQ_EXCHANGE: "sat.events"
  SERVICIO_REPORTES_URL: "http://svc-reportes:4001"
  SERVICIO_VALIDACION_URL: "http://svc-validacion:4002"
  SERVICIO_LOGISTICA_URL: "http://svc-logistica:4003"
