apiVersion: v1
kind: Secret
metadata:
  name: sat-secrets
type: Opaque
stringData:
  DB_PASSWORD_REPORTES: "password"
  DB_PASSWORD_VALIDACION: "password"
  DB_PASSWORD_LOGISTICA: "password"
  RABBITMQ_DEFAULT_USER: "sat-user"
  RABBITMQ_DEFAULT_PASS: "sat-pass"
