apiVersion: v1
kind: Secret
metadata:
  name: sat-secrets
type: Opaque
stringData:
  RABBITMQ_URL: "amqp://sat-user:sat-pass@rabbitmq:5672/"
  DB_REPORTES_URL: "postgres://reportes:password@db-reportes:5432/reportes?sslmode=disable"
  DB_VALIDACION_URL: "postgres://validacion:password@db-validacion:5432/validacion?sslmode=disable"
  DB_LOGISTICA_URL: "postgres://logistica:password@db-logistica:5432/logistica?sslmode=disable"
  DB_PASSWORD_REPORTES: "password"
  DB_PASSWORD_VALIDACION: "password"
  DB_PASSWORD_LOGISTICA: "password"
  RABBITMQ_DEFAULT_USER: "sat-user"
  RABBITMQ_DEFAULT_PASS: "sat-pass"